### ISSUE TITLE
阅读过程中发现一个错别字

### ISSUE THREAD

**Issue by llag9810** [decert-me/blockchain-basic#3]
https://github.com/decert-me/blockchain-basic/blob/e20542a144d650256ebbdc4db84ef6325944643b/docs/2_how_bitcoin_work.md?plain=1#L28

这里应该是“根据椭圆曲线算法(ECDSA)计算出**公钥**”。

**Comment by panyinglei** [comment]
@llag9810  感谢您的反馈，我们将会尽快修复该bug

**Comment by panyinglei** [comment]
@llag9810  相关bug已经修复，我们将会不断改进，再次感谢您的反馈。
![image](https://github.com/decert-me/blockchain-basic/assets/58837426/69e09b06-3988-447f-8383-e8e0904f4b26)
