### ISSUE TITLE
docs/3_what_is_blockchain.md  部分文字重复

### ISSUE THREAD

**Issue by 0x-wen** [decert-me/blockchain-basic#5]
https://github.com/decert-me/blockchain-basic/blob/5d397c38acce65d0514d63c826ac151565f82aa7/docs/3_what_is_blockchain.md?plain=1#L16

![image](https://github.com/user-attachments/assets/2a9e7163-40a1-41ee-b728-9522952d136a)

**Comment by 0xdwong** [comment]
谢谢，已删除重复内容，
